{
 "title": "COVID Data",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "state",
    "query": "select distinct state from sandbox..jmm_covid_data"
   }
  ]
 },
 "panels": [
  {
   "title": "Positive Cases",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select\n\nc.date as 'time'\n,c.positiveIncrease as 'New Positive Cases'\n,avg(c1.positiveIncrease) as '7 Day Moving Avg'\nfrom sandbox..jmm_covid_data c\n\tleft join sandbox..jmm_covid_data c1 on c1.state=c.state and c1.date>dateadd(day,-7,c.date) and c1.date<=c.date\nwhere c.state='$state'\ngroup by \nc.date\n,c.positiveIncrease\norder by \nc.date\n\n"
    }
   ]
  },
  {
   "title": "Most Recent Values",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "select top 1 \r\ndataQualityGrade as 'Data Quality Grade'\r\nfrom sandbox..jmm_covid_data c\r\nwhere c.state='$state' --and c.date='2020-06-29'\r\n\r\norder by \r\nc.date desc"
    }
   ]
  },
  {
   "title": "Jefferson Co. KY",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 16 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 2 },
   "content": "State: $state\n\nData source:\n\n[The COVID Tracking Project](https://covidtracking.com/about-data)\n\n",
   "targets": [
    {
     "rawSql": "SELECT\n Time_Stamp AS \"time\",\n Application_Installation_ID\nFROM Application_Installation\nWHERE\n $__timeFilter(Time_Stamp)\nORDER BY Time_Stamp"
    }
   ]
  },
  {
   "title": "Positive Test Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "select\r\n\r\nc.date as 'time'\r\n--,convert(decimal(28,10),c.positiveIncrease)/case when c.negativeIncrease=0 then null else c.negativeincrease end as 'positive_rate'\r\n,avg(convert(decimal(28,10),c1.positiveIncrease)/case when c1.negativeIncrease=0 then null else c1.negativeincrease end) as '7 Day Moving Avg Positive Rate'\r\nfrom sandbox..jmm_covid_data c\r\n\tleft join sandbox..jmm_covid_data c1 on c1.state=c.state and c1.date>dateadd(day,-7,c.date) and c1.date<=c.date\r\nwhere c.state='$state'\r\ngroup by \r\nc.date\r\n--,convert(decimal(28,10),c.positiveIncrease)/case when c.negativeIncrease=0 then null else c.negativeincrease end\r\norder by \r\nc.date"
    },
    {
     "rawSql": "select\r\n\r\nc.date as 'time'\r\n,c.positiveIncrease+c.negativeIncrease as 'Tests'\r\n-- ,avg(c1.positiveIncrease+c1.negativeIncrease) as '7_dma_tests'\r\nfrom sandbox..jmm_covid_data c\r\n\t--left join sandbox..jmm_covid_data c1 on c1.state=c.state and c1.date>dateadd(day,-7,c.date) and c1.date<=c.date\r\nwhere c.state='$state'\r\n\r\norder by \r\nc.date"
    }
   ]
  },
  {
   "title": "Most Recent Data",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\r\n\r\nc.date as 'time'\r\n,convert(decimal(28,10),c.positiveIncrease)/case when c.negativeIncrease=0 then null else c.negativeincrease end as 'Positive Rate'\r\n,avg(convert(decimal(28,10),c1.positiveIncrease)/case when c1.negativeIncrease=0 then null else c1.negativeincrease end) as '7 Day MA Positive Rate'\r\nfrom sandbox..jmm_covid_data c\r\n\tleft join sandbox..jmm_covid_data c1 on c1.state=c.state and c1.date>dateadd(day,-7,c.date) and c1.date<=c.date\r\nwhere c.state='$state'\r\ngroup by \r\nc.date\r\n,convert(decimal(28,10),c.positiveIncrease)/case when c.negativeIncrease=0 then null else c.negativeincrease end\r\norder by \r\nc.date"
    }
   ]
  },
  {
   "title": "Positive Cases - Jefferson Co. KY",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select s.date as 'time', s.new_cases as 'New Positive Cases'\r\n,s.new_cases_7dma as '7 Day Moving Avg' \r\nfrom sandbox..jmm_covid_data_nyt_county_view s where s.state='Kentucky' and s.county='Jefferson'\r\n"
    }
   ]
  },
  {
   "title": "Hospitalizations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "select\n\nc.date as 'time'\n,c.hospitalizedIncrease as 'New Hospitalizations'\n,avg(c1.hospitalizedIncrease) as '7 Day Moving Avg'\nfrom sandbox..jmm_covid_data c\n\tleft join sandbox..jmm_covid_data c1 on c1.state=c.state and c1.date>dateadd(day,-7,c.date) and c1.date<=c.date\nwhere c.state='$state'\ngroup by \nc.date\n,c.hospitalizedIncrease\norder by \nc.date\n\n"
    }
   ]
  },
  {
   "title": "Most Recent Values",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n\nc.date as 'time'\n,c.hospitalizedIncrease as 'New Hospitalizations'\n,avg(c1.hospitalizedIncrease) as '7 Day Moving Avg'\nfrom sandbox..jmm_covid_data c\n\tleft join sandbox..jmm_covid_data c1 on c1.state=c.state and c1.date>dateadd(day,-7,c.date) and c1.date<=c.date\nwhere c.state='$state'\ngroup by \nc.date\n,c.hospitalizedIncrease\norder by \nc.date\n\n"
    }
   ]
  },
  {
   "title": "National Positive Cases",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "with x as (\nselect\n\nc.date as 'time'\n,sum(c.positiveIncrease) as 'New Positive Cases'\nfrom sandbox..jmm_covid_data c\n\t--left join sandbox..jmm_covid_data c1 on c1.state=c.state and c1.date>dateadd(day,-7,c.date) and c1.date<=c.date\ngroup by \nc.date\n)\n\nselect\n\nx.time\n,x.[New Positive Cases]\n,avg(x1.[New Positive Cases]) as '7 Day Moving Avg'\n\nfrom x\n\tleft join x x1 on x1.time>dateadd(day,-7,x.time) and x1.time<=x.time\ngroup by \nx.time\n,x.[New Positive Cases]\norder by x.time"
    }
   ]
  },
  {
   "title": "Most Recent Natl Values",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 12 }
   ]
  }
 ]
}